# Generated by Django 4.2 on 2023-04-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_notes_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notes",
            name="user",
        ),
    ]
